#ifndef __FEATURE_SETTINGS_H
#define __FEATURE_SETTINGS_H	

#define ADD_TERRAINS true
#define TOGGLE_TMS false
#define ELECTRIC_TERRAIN_MOVE_ANIM 351
#define GRASSY_TERRAIN_MOVE_ANIM 312
#define MISTY_TERRAIN_MOVE_ANIM 54
#define PSYCHIC_TERRAIN_MOVE_ANIM 505

// MESSAGE IDs
// Game Text - File 6
#define BAG_ITEMUSED_MSGID 63
#define BAG_REPELEND_MSGID 64
// Game Text - File 17
#define BATTLE_ASSAULTVEST_MSGID 201
#define BATTLE_ELECTRIC_TERRAIN_MSGID 202
#define BATTLE_GRASSY_TERRAIN_MSGID 203
#define BATTLE_MISTY_TERRAIN_MSGID 204
#define BATTLE_PSYCHIC_TERRAIN_MSGID 205
#define BATTLE_TERRAIN_END_MSGID 206
// Game Text - File 18
#define BATTLE_CLEARAMULET_MSGID 878
#define BATTLE_ELECTRIC_TERRAIN_STATUS_MSGID 1159
#define BATTLE_MISTY_TERRAIN_STATUS_MSGID 1162
// Game Text - File 178
#define POKELIST_NATURECHANGE_MSGID 73
#define POKELIST_ABILITYCHANGE_MSGID 74
#define POKELIST_IVMODALL_MSGID 75
#define POKELIST_IVMODSINGLE_MSGID 76


#endif