<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;Debug_ParagonLite;Release_ParagonLite;Debug_Cascade;Release_Cascade</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug_ParagonLite' ">
      <DefineConstants>TRACE;PARAGONLITE</DefineConstants>
      <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release_ParagonLite' ">
      <DefineConstants>TRACE;PARAGONLITE</DefineConstants>
      <Optimize>true</Optimize>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug_Cascade' ">
      <DefineConstants>TRACE;CASCADE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release_Cascade' ">
      <DefineConstants>TRACE;CASCADE</DefineConstants>
    </PropertyGroup>

</Project>
